# Default initial positions for robot's ros2_control fake system

initial_positions:
  ${name}_joint_1: -0.23921483
  ${name}_joint_2: 0.85088292
  ${name}_joint_3: 0.1007404
  ${name}_joint_4: 2.40223628
  ${name}_joint_5: -0.07318166
  ${name}_joint_6: -1.70646077
  ${name}_joint_7: -1.63699667
  robotiq_85_left_knuckle_joint: 0.0
