# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ${name}_joint_trajectory_controller
    - robotiq_85_controller

  ${name}_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ${name}_joint_1
      - ${name}_joint_2
      - ${name}_joint_3
      - ${name}_joint_4
      - ${name}_joint_5
      - ${name}_joint_6
      - ${name}_joint_7

  robotiq_85_controller:
    type: GripperCommand
    joints:
      - robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true
