# Default initial positions for a200-0000's ros2_control fake system

initial_positions:
  arm_0_joint_1: 0
  arm_0_joint_2: 0
  arm_0_joint_3: 0
  arm_0_joint_4: 0
  arm_0_joint_5: 0
  arm_0_joint_6: 0
  arm_0_joint_7: 0