# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_0_joint_trajectory_controller

  arm_0_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: True
    joints:
      - arm_0_joint_1
      - arm_0_joint_2
      - arm_0_joint_3
      - arm_0_joint_4
      - arm_0_joint_5
      - arm_0_joint_6
      - arm_0_joint_7

