# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_0_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_0_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_0_joint_1
      - arm_0_joint_2
      - arm_0_joint_3
      - arm_0_joint_4
      - arm_0_joint_5
      - arm_0_joint_6
      - arm_0_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
